Repository Sunbird-Ed/SunbirdEd-portal, pull requests merged in 2022-10, with the labels that each got.

#8311 Issue #SB-0000 fix test case of unenroll-batch with 82.35% coverage
  src/app/client/src/app/modules/learn/components/batch/unenroll-batch/unenroll-batch.component.spec.ts
Labels: test_case

#8314 Issue #ED-28 fix:spacing issue fixed
  src/app/client/src/app/modules/observation/components/submissions/submission.component.html
Labels: defect

#8318 Issue #SB-0000 fix:"Added a keycloak api to whitelist API"
  src/app/helpers/whitelistApis.js
Labels: configuration

#8319 SB-30824 fix: added text for user experience
  src/app/client/src/app/modules/public/module/signup/components/signup-basic-info/signup-basic-info.component.html
  src/app/resourcebundles/data/consumption/as.properties
  src/app/resourcebundles/data/consumption/bn.properties
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/data/consumption/gu.properties
  src/app/resourcebundles/data/consumption/hi.properties
  src/app/resourcebundles/data/consumption/kn.properties
  src/app/resourcebundles/data/consumption/mr.properties
  src/app/resourcebundles/data/consumption/or.properties
  src/app/resourcebundles/data/consumption/pa.properties
  src/app/resourcebundles/data/consumption/ta.properties
  src/app/resourcebundles/data/consumption/te.properties
  src/app/resourcebundles/data/consumption/ur.properties
  src/app/resourcebundles/json/as.json
  src/app/resourcebundles/json/bn.json
  src/app/resourcebundles/json/en.json
  src/app/resourcebundles/json/gu.json
  src/app/resourcebundles/json/hi.json
  src/app/resourcebundles/json/kn.json
  src/app/resourcebundles/json/mr.json
  src/app/resourcebundles/json/or.json
  src/app/resourcebundles/json/pa.json
  src/app/resourcebundles/json/ta.json
  src/app/resourcebundles/json/te.json
  src/app/resourcebundles/json/ur.json
Labels: bug

#8321 Issue #0000 Css code cleanup in mygroups
  src/app/client/src/app/modules/groups/components/activity/activity-details/activity-details.component.scss
  src/app/client/src/app/modules/groups/components/activity/activity-search/activity-search.component.scss
  src/app/client/src/app/modules/groups/components/add-member/add-member.component.scss
  src/app/client/src/app/modules/groups/components/create-edit-group/create-edit-group.component.scss
  src/app/client/src/app/modules/groups/components/ftu-popup/ftu-popup.component.scss
  src/app/client/src/app/modules/groups/components/group-details/group-details.component.scss
  src/app/client/src/app/modules/groups/components/group-members/group-members.component.scss
  src/app/client/src/app/modules/groups/components/my-groups/my-groups.component.scss
Labels: enhancement

#8322 Issue #ED-239 feature: Added Azure upload function for desktop app crash log file upload
  src/app/client/package.json
  src/app/helpers/cloudStorage/AzureStorageService.js
  src/app/helpers/cloudStorage/BaseStorageService.js
  src/app/helpers/cloudStorage/GCPStorageService.js
  src/app/package.json
  src/app/routes/desktopAppRoutes.js
  src/desktop/package.json
Labels: Feature

#8326 Issue #ED-239 feature: Added AWS upload function for desktop app crash log file upload
  build.sh
  src/app/helpers/cloudStorage/AWSStorageService.js
  src/app/helpers/cloudStorage/AzureStorageService.js
  src/app/package.json
  src/app/yarn.lock
Labels: enhancement, Feature

#8328 Issue #ED-239 feature: Added GCLOUD upload function for desktop app crash log file upload
  src/app/helpers/cloudStorage/AzureStorageService.js
  src/app/helpers/cloudStorage/GCPStorageService.js
Labels: enhancement, Feature

#8330 Issue #RRHE-48 feat:Customized configurable filters for filtered task detail report type
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.html
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.spec.data.ts
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.spec.ts
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
  src/app/client/src/app/modules/program-dashboard/program-dashboard.module.ts
  src/app/client/src/app/modules/program-dashboard/shared/pd-filters/pd-filters.component.html
  src/app/client/src/app/modules/program-dashboard/shared/pd-filters/pd-filters.component.spec.ts
  src/app/client/src/app/modules/program-dashboard/shared/pd-filters/pd-filters.component.ts
Labels: enhancement

#8334 Issue #ED-366 fix:Getting console error-while opening the contents of…
  src/app/client/src/app/modules/shared/services/window-scroll/window-scroll.service.ts
Labels: defect
