Repository Sunbird-Ed/SunbirdEd-portal, pull requests merged in 2022-12, with the labels that each got.

#8379 Issue #SB-0000 Update:sl-questionnaire and sl-reports-library angular update to V11
  README.md
  src/app/client/package.json
  src/app/client/yarn.lock
Labels: angular_upgradation

#8381 Issue #SB-31172 fix:Overflow of content in the observation items of observation details page
  src/app/client/src/app/modules/observation/components/observation-details/observation-details.component.scss
Labels: bug

#8383 Issue #ED-536 fix: Form service plugin updated to 0.0.15
  src/app/package.json
  src/app/yarn.lock
Labels: version update

#8393 Issue #ED-0000 fix: Updated client cloud services for better logging
  src/app/package.json
  src/app/yarn.lock
Labels: documentation

#8394 Issue #ED-0000 fix: client cloud services GCP added upload method
  src/app/package.json
  src/app/yarn.lock
Labels: dependencies

#8398 Issue #ED-420 CSS cleanup and themes cleanup & SASS migration
  src/app/client/src/app/modules/dashboard/components/report/report.component.scss
  src/app/client/src/app/modules/learn/components/course-consumption/course-player/course-player.component.scss
  src/app/client/src/app/modules/public/module/course/components/course-consumption/public-course-player/public-course-player.component.scss
  src/app/client/src/app/modules/public/module/explore/components/explore-curriculum-courses/explore-curriculum-courses.component.scss
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.scss
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.scss
  src/app/client/src/app/modules/report/components/report-view/report-view.component.scss
  src/app/client/src/app/modules/resource/components/curriculum-courses/curriculum-courses.component.scss
  src/app/client/src/app/modules/shared-feature/components/collection-player/collection-player.component.scss
  src/app/client/src/app/modules/shared-feature/components/content-player/content-player.component.scss
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.scss
  src/app/client/src/assets/styles/pages/_reports.scss
Labels: enhancement, css cleanup

#8397 Issue #ED-517 fix: Stepper config of onboarding-flow in portal
  src/app/client/src/app/app.component.html
  src/app/client/src/app/app.component.spec.ts
  src/app/client/src/app/app.component.ts
  src/app/client/src/app/app.module.ts
  src/app/client/src/app/modules/shared-feature/components/onboarding-user-selection/onboarding-user-selection.component.ts
  src/app/client/src/app/modules/shared-feature/components/profile-framework-popup/profile-framework-popup.component.ts
  src/app/client/src/app/modules/user-onboarding/components/index.ts
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.html
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.models.ts
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.scss
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.spec.data.ts
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.spec.ts
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.ts
  src/app/client/src/app/modules/user-onboarding/index.ts
  src/app/client/src/app/modules/user-onboarding/user-onboarding.module.ts
  src/app/client/src/app/plugins/location/components/delegate/sb-form-location-selection.delegate.ts
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.html
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.ts
  src/app/client/yarn.lock
Labels: story

#8403 Hotfix: Observation with rubric without criteria level report
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.spec.data.ts
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
Labels: hot-fix

#8414 Issue #SB-0000 test: Unit test for search filter and managed user service
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.spec.ts
  src/app/client/src/app/modules/core/services/managed-user/managed-user.service.spec.ts
Labels: test_case

#8417 Issue #ED-306 fix: Page level filter configurations on portal and desktop app
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.html
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.spec.ts
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.ts
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
Labels: enhancement

#8421 Release 5.1.0
  src/app/client/src/app/modules/learn/components/batch/update-course-batch/update-course-batch.component.html
  src/app/client/src/app/modules/learn/components/batch/update-course-batch/update-course-batch.component.ts
Labels: defect

#8422 Issue #ED-577 fix: API call checks added
  src/app/client/src/app/modules/dashboard/components/course-progress/course-progress.component.ts
Labels: defect

#8423 Issue #SB-0000 fix: Added test cases
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.spec.ts
  src/app/client/src/app/modules/dashboard/services/usage/usage.service.spec.ts
  src/app/client/src/app/plugins/location/services/location/location.service.spec.ts
  src/app/client/src/app/plugins/profile/components/submit-teacher-details/submit-teacher-details.component.spec.data.ts
  src/app/client/src/app/plugins/profile/components/submit-teacher-details/submit-teacher-details.component.spec.ts
  src/app/client/src/app/plugins/profile/services/profile/profile.service.spec.ts
Labels: test_case

#8431 Issue #ED-631 fix: start and end date allowed only after the user chooses a resource
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.html
Labels: defect

#8432 Update README.md for developer instrauctions
  README.md
  local_setup.sh
Labels: documentation

#8433 Issue #ED-638 fix: Non-logged in user is taken to the login screen after clicking on observation tile of browse other categories
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
Labels: defect

#8435 Issue #ED-646 fix: pop-up button alignment in the questionnaire page
  src/app/client/src/app/modules/questionnaire/questionnaire/questionnaire.component.scss
Labels: defect

#8440 Issue #ED-637 fix: Updated moment version to 2.29.1
  src/app/client/package.json
  src/app/client/yarn.lock
Labels: defect
