Repository Sunbird-Ed/SunbirdEd-portal, pull requests merged in 2022-11, with the labels that each got.

#8335 Issue #SB-0000 env changes
  src/app/helpers/environmentVariablesHelper.js
Labels: enhancement, configuration

#8336 Issue #SB-0000 fix: readme.md file changes
  src/app/client/README.md
Labels: documentation

#8337 Issue #SB-0000 fix:Added testcases for service files
  src/app/client/src/app/modules/dashboard/services/download/download.service.spec.ts
  src/app/client/src/app/modules/dashboard/services/organization/organization.service.spec.ts
  src/app/client/src/app/modules/dashboard/services/renderer/renderer.service.spec.ts
  src/app/client/src/app/modules/dashboard/services/usage/usage.service.spec.ts
Labels: test_case

#8338 Issue #SB-0000 fix: Merge release-5.0.0 into release-5.0.1
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.html
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.scss
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.spec.data.ts
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.spec.ts
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
  src/app/client/src/app/modules/program-dashboard/program-dashboard.module.ts
  src/app/client/src/app/modules/program-dashboard/shared/pd-filters/pd-filters.component.html
  src/app/client/src/app/modules/program-dashboard/shared/pd-filters/pd-filters.component.spec.ts
  src/app/client/src/app/modules/program-dashboard/shared/pd-filters/pd-filters.component.ts
  src/app/client/src/app/modules/public/module/signup/components/signup-basic-info/signup-basic-info.component.html
  src/app/resourcebundles/data/consumption/as.properties
  src/app/resourcebundles/data/consumption/bn.properties
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/data/consumption/gu.properties
  src/app/resourcebundles/data/consumption/hi.properties
  src/app/resourcebundles/data/consumption/kn.properties
  src/app/resourcebundles/data/consumption/mr.properties
  src/app/resourcebundles/data/consumption/or.properties
  src/app/resourcebundles/data/consumption/pa.properties
  src/app/resourcebundles/data/consumption/ta.properties
  src/app/resourcebundles/data/consumption/te.properties
  src/app/resourcebundles/data/consumption/ur.properties
  src/app/resourcebundles/json/as.json
  src/app/resourcebundles/json/bn.json
  src/app/resourcebundles/json/en.json
  src/app/resourcebundles/json/gu.json
  src/app/resourcebundles/json/hi.json
  src/app/resourcebundles/json/kn.json
  src/app/resourcebundles/json/mr.json
  src/app/resourcebundles/json/or.json
  src/app/resourcebundles/json/pa.json
  src/app/resourcebundles/json/ta.json
  src/app/resourcebundles/json/te.json
  src/app/resourcebundles/json/ur.json
Labels: branch_merge

#8339 Issue #SB-0000 fix: Merge release-5.0.0.1 into release-5.0.1
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.html
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
Labels: branch_merge

#8340 Issue #SB-0000 fix: Merge release-5.0.1 into release-5.0.2
  .vscode/settings.json
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.html
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.scss
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.spec.data.ts
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.spec.ts
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
  src/app/client/src/app/modules/program-dashboard/program-dashboard.module.ts
  src/app/client/src/app/modules/program-dashboard/shared/pd-filters/pd-filters.component.html
  src/app/client/src/app/modules/program-dashboard/shared/pd-filters/pd-filters.component.spec.ts
  src/app/client/src/app/modules/program-dashboard/shared/pd-filters/pd-filters.component.ts
  src/app/client/src/app/modules/public/module/signup/components/signup-basic-info/signup-basic-info.component.html
  src/app/resourcebundles/data/consumption/as.properties
  src/app/resourcebundles/data/consumption/bn.properties
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/data/consumption/gu.properties
  src/app/resourcebundles/data/consumption/hi.properties
  src/app/resourcebundles/data/consumption/kn.properties
  src/app/resourcebundles/data/consumption/mr.properties
  src/app/resourcebundles/data/consumption/or.properties
  src/app/resourcebundles/data/consumption/pa.properties
  src/app/resourcebundles/data/consumption/ta.properties
  src/app/resourcebundles/data/consumption/te.properties
  src/app/resourcebundles/data/consumption/ur.properties
  src/app/resourcebundles/json/as.json
  src/app/resourcebundles/json/bn.json
  src/app/resourcebundles/json/en.json
  src/app/resourcebundles/json/gu.json
  src/app/resourcebundles/json/hi.json
  src/app/resourcebundles/json/kn.json
  src/app/resourcebundles/json/mr.json
  src/app/resourcebundles/json/or.json
  src/app/resourcebundles/json/pa.json
  src/app/resourcebundles/json/ta.json
  src/app/resourcebundles/json/te.json
  src/app/resourcebundles/json/ur.json
Labels: branch_merge

#8341 Issue #SB-0000 fix: Merge release-5.0.2 into release-5.0.3
  .gitignore
  .vscode/settings.json
  src/app/client/README.md
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.html
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.scss
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.spec.data.ts
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.spec.ts
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
  src/app/client/src/app/modules/program-dashboard/program-dashboard.module.ts
  src/app/client/src/app/modules/program-dashboard/shared/pd-filters/pd-filters.component.html
  src/app/client/src/app/modules/program-dashboard/shared/pd-filters/pd-filters.component.spec.ts
  src/app/client/src/app/modules/program-dashboard/shared/pd-filters/pd-filters.component.ts
  src/app/client/src/app/modules/public/module/signup/components/signup-basic-info/signup-basic-info.component.html
  src/app/helpers/environmentVariablesHelper.js
  src/app/resourcebundles/data/consumption/as.properties
  src/app/resourcebundles/data/consumption/bn.properties
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/data/consumption/gu.properties
  src/app/resourcebundles/data/consumption/hi.properties
  src/app/resourcebundles/data/consumption/kn.properties
  src/app/resourcebundles/data/consumption/mr.properties
  src/app/resourcebundles/data/consumption/or.properties
  src/app/resourcebundles/data/consumption/pa.properties
  src/app/resourcebundles/data/consumption/ta.properties
  src/app/resourcebundles/data/consumption/te.properties
  src/app/resourcebundles/data/consumption/ur.properties
  src/app/resourcebundles/json/as.json
  src/app/resourcebundles/json/bn.json
  src/app/resourcebundles/json/en.json
  src/app/resourcebundles/json/gu.json
  src/app/resourcebundles/json/hi.json
  src/app/resourcebundles/json/kn.json
  src/app/resourcebundles/json/mr.json
  src/app/resourcebundles/json/or.json
  src/app/resourcebundles/json/pa.json
  src/app/resourcebundles/json/ta.json
  src/app/resourcebundles/json/te.json
  src/app/resourcebundles/json/ur.json
Labels: branch_merge

#8342 Graphs and tables enabled
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.html
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
Labels: defect

#8344 Issue #SB-0000 fix:Added testcases for dial-code-card component and signup-service and Readme.md file changes
  README.md
  src/app/client/src/app/modules/dial-code-search/components/dial-code-card/dial-code-card.component.spec.ts
  src/app/client/src/app/modules/public/module/signup/services/signup/signup.service.spec.data.ts
  src/app/client/src/app/modules/public/module/signup/services/signup/signup.service.spec.ts
Labels: test_case

#8343 Issue #SB-0000 fix: Updated portal version to 5.0.3
  src/app/client/package.json
  src/app/package.json
  src/desktop/package.json
Labels: branch_merge

#8347 Issue #SB-0000 fix: Added testcases for landingpage-guard and questio…
  src/app/client/src/app/modules/public/services/landingpage-guard/landingpage-guard.spec.ts
  src/app/client/src/app/modules/questionnaire/questionnaire.service.spec.ts
Labels: test_case

#8349 Issue #ED-389 feat: Updated resource bundles to fetch from Blob Storage
  src/app/helpers/resourceBundles/index.js
  src/app/package.json
Labels: enhancement, Feature

#8350 Issue #SB-0000 fix: Added testcases
  src/app/client/src/app/modules/recover-account/components/recover-account/recover-acount.component.spec.ts
  src/app/client/src/app/modules/recover-account/services/recover-account/recover-account.service.spec.ts
  src/app/client/src/app/modules/shared/services/config/config.service.spec.ts
  src/app/client/src/app/service/CsLibInitializer/cs-lib-initializer.service.spec.ts
  src/app/client/src/app/service/popup-control.service.spec.ts
Labels: test_case

#8352 Issue #ED-389 feat: Reverted sunbird resource bundle externalise
  src/app/client/package.json
  src/app/helpers/resourceBundles/index.js
  src/app/package.json
  src/desktop/package.json
Labels: enhancement

#8356 Issue #SB-0000 fix: Added testcases
  src/app/client/src/app/plugins/location/services/location/location.service.spec.data.ts
  src/app/client/src/app/plugins/location/services/location/location.service.spec.ts
  src/app/client/src/app/plugins/profile/components/update-contact-details/update-contact-details.spec.ts
  src/app/client/src/app/plugins/profile/services/profile/profile.service.spec.ts
Labels: test_case

#8357 Issue #ED-393 feat: Externalised CSP package implemented in portal backend
  src/app/helpers/cloudStorage/AWSStorageService.js
  src/app/helpers/cloudStorage/AzureStorageService.js
  src/app/helpers/cloudStorage/BaseStorageService.js
  src/app/helpers/cloudStorage/GCPStorageService.js
  src/app/helpers/cloudStorage/index.js
  src/app/package.json
  src/app/yarn.lock
Labels: enhancement

#8359 Issue #SB-0000 fix: Added testcases
  src/app/client/src/app/modules/telemetry/directives/telemetry-end/telemetry-end.directive.spec.ts
  src/app/client/src/app/modules/telemetry/directives/telemetry-error/telemetry-error.directive.spec.ts
  src/app/client/src/app/modules/telemetry/directives/telemetry-impression/telemetry-impression.directive.spec.data.ts
  src/app/client/src/app/modules/telemetry/directives/telemetry-impression/telemetry-impression.directive.spec.ts
  src/app/client/src/app/modules/telemetry/directives/telemetry-share/telemetry-share.directive.spec.ts
  src/app/client/src/app/modules/telemetry/directives/telemetry-start/telemetry-start.directive.spec.ts
  src/app/client/src/app/modules/uci-admin/components/uci/uci.component.spec.ts
Labels: test_case

#8360 Issue #SB-0000 fix: Updated sb-notification package to angular 9
  src/app/client/package.json
  src/app/client/src/app/modules/notification/notification.module.ts
  src/app/client/src/app/modules/notification/services/notification/notification-service-impl.ts
  src/app/client/yarn.lock
Labels: enhancement, angular_upgradation

#8361 Issue #SB-0000 fix: Updated sb-notification package to angular 10
  src/app/client/package.json
  src/app/client/yarn.lock
Labels: enhancement, angular_upgradation

#8365 Issue #SB-0000 fix: Upgrade chatbot and sb-notification library
  src/app/client/package.json
  src/app/client/src/app/app.module.ts
  src/app/client/yarn.lock
Labels: enhancement, angular_upgradation

#8366 Issue #SB-0000 fix: Added testcases
  src/app/client/src/app/modules/public/module/sign-in/sso/components/update-contact/update-contact.component.spec.ts
  src/app/client/src/app/modules/shared/services/activity-dashboard/activity-dashboard.service.spec.ts
  src/app/client/src/app/plugins/profile/components/account-recovery-info/account-recovery-info.component.spec.ts
Labels: test_case

#8368 Issue #SB-0000 fix: Upgrade chatbot library to NG 11
  src/app/client/package.json
  src/app/client/yarn.lock
Labels: angular_upgradation

#8371 Issue ED-521 fix: Update CSP variables changes in environment variables
  .github/pull_request_template.md
  README.md
  src/app/client/package.json
  src/app/client/yarn.lock
  src/app/helpers/environmentVariablesHelper.js
Labels: documentation, configuration, angular_upgradation

#8372 Issue #SB-0000 fix: Upgraded SunbirdEd forms library to Angular v11
  src/app/client/package.json
  src/app/client/yarn.lock
Labels: enhancement, angular_upgradation

#8373 Issue ED-521 fix: client cloud services updated
  README.md
  src/app/helpers/resourceBundleHelper.js
  src/app/package.json
  src/app/routes/reportRoutes.js
  src/app/yarn.lock
Labels: version update

#8374 Issue #SB-0000 Updated:common-consumption to Angular-v11
  src/app/client/angular.json
  src/app/client/package.json
  src/app/client/src/app/modules/certificate/certificate.module.ts
  src/app/client/src/app/modules/content-search/components/global-search-filter/global-search-filter.component.ts
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.ts
  src/app/client/src/app/modules/content-search/content-search.module.ts
  src/app/client/src/app/modules/core/core.module.ts
  src/app/client/src/app/modules/dashboard/dashboard.module.ts
  src/app/client/src/app/modules/dial-code-search/dial-code-search.module.ts
  src/app/client/src/app/modules/explore-page/explore-page.module.ts
  src/app/client/src/app/modules/groups/groups.module.ts
  src/app/client/src/app/modules/learn/components/course-consumption/assessment-player/assessment-player.component.ts
  src/app/client/src/app/modules/learn/components/course-consumption/course-player/course-player.component.ts
  src/app/client/src/app/modules/learn/course-consumption.module.ts
  src/app/client/src/app/modules/learn/learn.module.ts
  src/app/client/src/app/modules/notification/components/in-app-notification/in-app-notification.component.ts
  src/app/client/src/app/modules/notification/notification.module.ts
  src/app/client/src/app/modules/observation/observation.module.ts
  src/app/client/src/app/modules/player-helper/components/content-actions/actionButtons.ts
  src/app/client/src/app/modules/player-helper/player-helper.module.ts
  src/app/client/src/app/modules/public/module/course/components/course-consumption/public-course-player/public-course-player.component.ts
  src/app/client/src/app/modules/public/module/course/course.module.ts
  src/app/client/src/app/modules/public/module/explore/explore.module.ts
  src/app/client/src/app/modules/public/module/help/help.module.ts
  src/app/client/src/app/modules/public/module/offline/offline.module.ts
  src/app/client/src/app/modules/public/module/player/player.module.ts
  src/app/client/src/app/modules/resource/modules/player/player.module.ts
  src/app/client/src/app/modules/resource/resource.module.ts
  src/app/client/src/app/modules/search/search.module.ts
  src/app/client/src/app/modules/shared-feature/components/collection-player/collection-player.component.ts
  src/app/client/src/app/modules/shared-feature/shared-feature.module.ts
  src/app/client/src/app/plugins/profile/profile.module.ts
  src/app/client/yarn.lock
  src/app/yarn.lock
Labels: enhancement, angular_upgradation

#8377 Issue #ED-384 css cleanup px to rem, color values to variables, remov…
  src/app/client/src/app/modules/certificate/components/certificate-configuration/certificate-configuration.component.scss
  src/app/client/src/app/modules/certificate/components/svg-editor/svg-editor.component.scss
  src/app/client/src/app/modules/content-search/components/global-search-filter/global-search-filter.component.scss
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.scss
  src/app/client/src/app/modules/core/components/main-footer/main-footer.component.scss
  src/app/client/src/app/modules/core/components/main-header/main-header.component.scss
  src/app/client/src/app/modules/dashboard/components/course-dashboard/course-dashboard.component.scss
  src/app/client/src/app/modules/dashboard/components/dashboard-sidebar/dashboard-sidebar.component.scss
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.scss
  src/app/client/src/assets/styles/components/_buttons--.scss
  src/app/client/src/assets/styles/components/_form.scss
  src/app/client/src/assets/styles/components/_labels.scss
  src/app/client/src/assets/styles/components/_modal.scss
  src/app/client/src/assets/styles/components/_search.scss
  src/app/client/src/assets/styles/components/_tables.scss
  src/app/client/src/assets/styles/global.scss
  src/app/client/src/assets/styles/layout/_header.scss
  src/app/client/src/assets/styles/legacy.scss
  src/app/client/src/assets/styles/pages/_course-player.scss
  src/app/client/src/assets/styles/pages/_sbt-dropdown.scss
  src/app/client/src/assets/styles/pages/_sbt-filter.scss
  src/app/client/src/assets/styles/vendors/_slick.scss
Labels: enhancement, css cleanup
