Repository Sunbird-Ed/SunbirdEd-portal, pull requests merged in 2022-07, with the labels that each got.

#8184 Issue #SB-0000 fix: Update portal version
  src/app/package.json
Labels: version update

#8187 4.10.2
  src/app/client/src/app/modules/learn/components/batch/batch-details/batch-details.component.html
  src/app/client/src/app/modules/learn/components/course-consumption/course-consumption-header/course-consumption-header.component.html
  src/app/client/src/app/modules/public/module/course/components/batch/public-batch-details/public-batch-details.component.html
  src/app/client/src/app/modules/public/module/course/components/course-consumption/public-course-consumption-page/public-course-consumption-page.component.html
Labels: enhancement

#8193 - Issue #SB-0000 fix: Merge release-4.10.1 into release-4.10.2
  src/app/client/package.json
  src/app/client/src/app/modules/core/services/user/user.service.ts
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
  src/app/client/src/app/modules/learn/components/batch/create-batch/create-batch.component.html
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.scss
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.scss
  src/app/client/yarn.lock
Labels: branch_merge

#8197 Issue #SB-30480 fix: Update Board labels in phase 1
  src/app/client/src/app/modules/shared/pipes/transposeTerms/transposeTerms.pipe.ts
Labels: Feature

#8198 Issue #SB-30480 fix: Updated Medium labels in phase 2
  src/app/client/package.json
  src/app/client/src/app/modules/dial-code-search/components/dial-code-card/dial-code-card.component.html
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html
  src/app/client/src/app/modules/learn/components/course-consumption/course-details/course-details.component.html
  src/app/client/src/app/modules/player-helper/components/collection-player-metadata/collection-player-metadata.component.html
  src/app/client/src/app/modules/player-helper/components/content-player-metadata/content-player-metadata.component.html
  src/app/client/src/app/modules/player-helper/components/contentplayer-page/contentplayer-page.component.html
  src/app/client/src/app/modules/public/module/course/components/course-consumption/public-course-player/public-course-player.component.html
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.html
  src/app/client/src/app/modules/search/components/user-filter/user-filter.component.html
  src/app/client/src/app/modules/shared-feature/components/profile-framework-popup/profile-framework-popup.component.html
  src/app/client/src/app/modules/shared/components/card/card.component.html
  src/app/client/src/app/modules/shared/pipes/transposeTerms/transposeTerms.pipe.ts
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.html
  src/app/package.json
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/json/en.json
Labels: Feature

#8199 Issue Fix:#SB-30483 Course page enhancements
  src/app/client/src/app/modules/learn/services/course-consumption/course-consumption.service.ts
  src/app/client/src/app/modules/public/module/course/components/course-consumption/public-course-consumption-page/public-course-consumption-page.component.html
Labels: enhancement

#8201 Issue #SB-30480 fix: Update Grade level and Class labels in phase 1
  src/app/client/src/app/modules/dial-code-search/components/dial-code-card/dial-code-card.component.html
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html
  src/app/client/src/app/modules/learn/components/course-consumption/course-details/course-details.component.html
  src/app/client/src/app/modules/org-management/components/status/status.component.html
  src/app/client/src/app/modules/player-helper/components/collection-player-metadata/collection-player-metadata.component.html
  src/app/client/src/app/modules/player-helper/components/content-player-metadata/content-player-metadata.component.html
  src/app/client/src/app/modules/player-helper/components/contentplayer-page/contentplayer-page.component.html
  src/app/client/src/app/modules/public/module/course/components/course-consumption/public-course-player/public-course-player.component.html
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.html
  src/app/client/src/app/modules/search/components/user-filter/user-filter.component.html
  src/app/client/src/app/modules/search/components/user-profile/user-profile.component.html
  src/app/client/src/app/modules/shared/components/card/card.component.html
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.html
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/json/en.json
Labels: Feature

#8202 Issue #SB-30480 fix: Update Subjects labels in phase 1
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.ts
  src/app/client/src/app/modules/dial-code-search/components/dial-code-card/dial-code-card.component.html
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
  src/app/client/src/app/modules/org-management/components/status/status.component.html
  src/app/client/src/app/modules/player-helper/components/collection-player-metadata/collection-player-metadata.component.html
  src/app/client/src/app/modules/player-helper/components/content-player-metadata/content-player-metadata.component.html
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.html
  src/app/client/src/app/modules/search/components/user-filter/user-filter.component.html
  src/app/client/src/app/modules/search/components/user-profile/user-profile.component.html
  src/app/client/src/app/modules/shared/components/card/card.component.html
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.html
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/json/en.json
Labels: Feature

#8206 Issue #SB-30612 course batch issue
  src/app/client/src/app/modules/learn/services/course-consumption/course-consumption.service.ts
Labels: bug

#8208 Issue #SB-30624 fix: During on boarding, in the location popup the submit button is not displayed properly
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.html
Labels: bug
