Repository Sunbird-Ed/SunbirdEd-portal, pull requests merged in 2022-09, with the labels that each got.

#8263 Issue #SB-30818 fix: Page refresh post preferences updated
  src/app/client/src/app/modules/public/module/signup/components/signup-onboarding-info/signup-onboarding-info.component.ts
Labels: defect

#8264 Issue #SB-30818 fix: Page refresh post preferences updated
  src/app/client/src/app/modules/public/module/signup/components/signup-onboarding-info/signup-onboarding-info.component.ts
Labels: defect

#8266 Issue #SB-30847 Portal : While editing the personal details, the UI w…
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.html
Labels: defect

#8268 Issue #SB-30818 fix: User location update for new gmail user login
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.ts
Labels: defect

#8271 Issue #SB-30871 fix: instance label updated for toast message
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/json/en.json
Labels: defect

#8272 Issue #SB-30871 fix: instance label updated for toast message
  src/app/resourcebundles/data/consumption/bn.properties
  src/app/resourcebundles/data/consumption/gu.properties
  src/app/resourcebundles/data/consumption/kn.properties
  src/app/resourcebundles/data/consumption/mr.properties
  src/app/resourcebundles/data/consumption/or.properties
  src/app/resourcebundles/data/consumption/pa.properties
  src/app/resourcebundles/data/consumption/ta.properties
  src/app/resourcebundles/data/consumption/ur.properties
  src/app/resourcebundles/json/bn.json
  src/app/resourcebundles/json/gu.json
  src/app/resourcebundles/json/kn.json
  src/app/resourcebundles/json/mr.json
  src/app/resourcebundles/json/or.json
  src/app/resourcebundles/json/pa.json
  src/app/resourcebundles/json/ta.json
  src/app/resourcebundles/json/ur.json
Labels: defect

#8276 Issue #SB-30903 Role is displayed in register page
  src/app/client/src/app/modules/public/module/signup/components/signup-onboarding-info/signup-onboarding-info.component.ts
Labels: defect

#8279 Issue #SB-0000 fix: Merge release-5.0.0 into release-5.0.1
  src/app/client/package.json
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.ts
  src/app/client/src/app/modules/dashboard/components/report/report.component.ts
  src/app/client/src/app/modules/discussion/components/forum/forum.component.spec.ts
  src/app/client/src/app/modules/manage/components/user-role-assign/user-role-assign.component.spec.ts
  src/app/client/src/app/modules/merge-account/components/merge-account-status/merge-account-status.component.spec.ts
  src/app/client/src/app/modules/observation/components/observation-details/observation-details.component.html
  src/app/client/src/app/modules/observation/components/observation-details/observation-details.component.ts
  src/app/client/src/app/modules/observation/components/observation-listing/observation-listing.component.ts
  src/app/client/src/app/modules/observation/components/submissions/submission.component.spec.ts
  src/app/client/src/app/modules/program-dashboard/shared/sb-table/sb-table.component.ts
  src/app/client/src/app/modules/public/module/signup/components/signup-onboarding-info/signup-onboarding-info.component.ts
  src/app/client/src/app/modules/public/module/signup/components/signup/signup.component.scss
  src/app/client/src/app/modules/shared-feature/components/onboarding-user-selection/onboarding-user-selection.component.spec.ts
  src/app/client/src/app/modules/shared/components/card-creation/card-creation.component.spec.ts
  src/app/client/src/app/modules/shared/services/config/editor.config.json
  src/app/client/src/app/modules/workspace/components/content-editors/new-collection-editor/new-collection-editor.component.ts
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.html
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.ts
  src/app/client/src/assets/styles/global.scss
  src/app/client/yarn.lock
  src/app/resourcebundles/data/consumption/bn.properties
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/data/consumption/gu.properties
  src/app/resourcebundles/data/consumption/hi.properties
  src/app/resourcebundles/data/consumption/kn.properties
  src/app/resourcebundles/data/consumption/mr.properties
  src/app/resourcebundles/data/consumption/or.properties
  src/app/resourcebundles/data/consumption/pa.properties
  src/app/resourcebundles/data/consumption/ta.properties
  src/app/resourcebundles/data/consumption/ur.properties
  src/app/resourcebundles/json/bn.json
  src/app/resourcebundles/json/en.json
  src/app/resourcebundles/json/gu.json
  src/app/resourcebundles/json/hi.json
  src/app/resourcebundles/json/kn.json
  src/app/resourcebundles/json/mr.json
  src/app/resourcebundles/json/or.json
  src/app/resourcebundles/json/pa.json
  src/app/resourcebundles/json/ta.json
  src/app/resourcebundles/json/ur.json
Labels: branch_merge

#8280 Issue #SB-30678 feat: Added Base Storage Service implementation
  .gitignore
  src/app/helpers/cloudStorage/BaseStorageService.js
  src/app/package.json
  src/app/yarn.lock
  src/desktop/main.ts
Labels: Feature

#8281 Issue #SB-30678 feat: Added Azure storage service
  src/app/helpers/cloudStorage/AWSStorageService.js
  src/app/helpers/cloudStorage/AzureStorageService.js
  src/app/helpers/cloudStorage/index.js
  src/app/helpers/reportHelper.js
  src/app/routes/reportRoutes.js
Labels: Feature

#8282 Issue #SB-30955 updating QUML player
  src/app/client/package.json
  src/app/client/yarn.lock
Labels: dependencies

#8286 Issue #SB-30678 feat: Added Azure storage service method added
  src/app/helpers/cloudStorage/AzureStorageService.js
  src/app/helpers/reportHelper.js
Labels: Feature

#8287 Issue #SB-0000 fix: Updated portal version to 5.0.1
  src/app/client/package.json
  src/app/package.json
  src/desktop/package.json
Labels: version update

#8288 5.0.1
  src/app/client/src/app/app.component.spec.ts
  src/app/client/src/app/app.component.ts
Labels: Feature

#8290 Issue #SB-30678 feat: Added Azure storage service method added
  src/app/helpers/cloudStorage/AzureStorageService.js
Labels: Feature

#8291 Issue #SB-30678 feat: Added Azure storage service method added response data method
  src/app/helpers/cloudStorage/AzureStorageService.js
Labels: Feature

#8293 SB-30824 fix : fix welcome to TENANT register on TENANT
  src/app/client/src/app/modules/public/module/signup/components/signup-basic-info/signup-basic-info.component.html
  src/app/client/src/app/modules/public/module/signup/components/signup-basic-info/signup-basic-info.component.ts
  src/app/client/src/app/modules/public/module/signup/components/signup/signup.component.html
Labels: bug

#8294 Issue #SB-30678 feat: Added Azure storage service method added getFileAsText
  src/app/helpers/cloudStorage/AzureStorageService.js
  src/app/helpers/cloudStorage/BaseStorageService.js
  src/app/helpers/resourceBundleHelper.js
Labels: Feature

#8292 Issue #SB-30496 UI breaking in course header
  src/app/client/src/app/modules/learn/components/course-consumption/course-consumption-header/course-consumption-header.component.html
  src/app/client/src/app/modules/shared-feature/components/content-player/content-player.component.html
Labels: bug

#8298 Issue #SB-30678 feat: Added AWS Storage implementation for - configuration variables
  src/app/helpers/cloudStorage/AzureStorageService.js
  src/app/helpers/cloudStorage/storageLogger.js
  src/app/helpers/environmentVariablesHelper.js
  src/app/package.json
  src/app/server.js
  src/app/yarn.lock
Labels: Feature

#8303 Issue #SB-30678 feat: Added GCP Storage implementation
  src/app/helpers/cloudStorage/AWSStorageService.js
  src/app/helpers/cloudStorage/AzureStorageService.js
  src/app/helpers/cloudStorage/BaseStorageService.js
  src/app/helpers/cloudStorage/GCPStorageService.js
  src/app/helpers/cloudStorage/index.js
  src/app/helpers/cloudStorage/storageLogger.js
  src/app/helpers/environmentVariablesHelper.js
  src/app/helpers/resourceBundleHelper.js
  src/app/package.json
  src/app/yarn.lock
Labels: Feature

#8304 Issue #SB:31005 fix:403 error resolved by giving access to PM and PD …
  src/app/routes/reportRoutes.js
Labels: defect

#8307 Issue #SB-0000 fix: Remove token print log from discussion forum routes
  src/app/client/src/app/modules/dashboard/components/course-progress/course-progress.component.ts
  src/app/routes/discussionsForum.js
Labels: bug

#8310 Issue #SB-31023 fix: Disabling Join Course button on Enrollment end date
  src/app/client/src/app/modules/learn/components/course-consumption/course-consumption-header/course-consumption-header.component.html
Labels: defect
