Repository Sunbird-Ed/SunbirdEd-portal, pull requests merged in 2022-08, with the labels that each got.

#8209 Issue #SB-30480 fix: Update labels for channel specific
  src/app/client/src/app/modules/core/components/main-header/main-header.component.ts
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html
  src/app/client/src/app/modules/search/components/home-search/home-search.component.html
  src/app/client/src/app/modules/search/components/home-search/home-search.component.ts
  src/app/client/src/app/modules/shared/services/genericResource/genericResource.service.ts
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/json/en.json
Labels: Feature

#8214 4.10.2
  src/app/client/src/app/plugins/location/components/delegate/sb-form-location-options.factory.ts
Labels: enhancement

#8222 Issues #SB-28247, #SB-28248 and #SB-30236 feat: Program dashboard Gra…
  src/app/client/package.json
  src/app/client/src/app/modules/dashboard/components/filter/filter.component.ts
  src/app/client/src/app/modules/dashboard/dashboard.module.ts
  src/app/client/src/app/modules/dashboard/services/report/report.service.ts
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.html
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.scss
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.spec.data.ts
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.spec.ts
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
  src/app/client/src/app/modules/program-dashboard/pipes/bigData/big-dat.pipe.spec.data.ts
  src/app/client/src/app/modules/program-dashboard/pipes/bigData/big-data.pipe.spec.ts
  src/app/client/src/app/modules/program-dashboard/pipes/bigData/big-data.pipe.ts
  src/app/client/src/app/modules/program-dashboard/pipes/chartType/chart-type.pipe.spec.data.ts
  src/app/client/src/app/modules/program-dashboard/pipes/chartType/chart-type.pipe.spec.ts
  src/app/client/src/app/modules/program-dashboard/pipes/chartType/chart-type.pipe.ts
  src/app/client/src/app/modules/program-dashboard/pipes/filterChart/filter-chart.pipe.spec.data.ts
  src/app/client/src/app/modules/program-dashboard/pipes/filterChart/filter-chart.pipe.spec.ts
  src/app/client/src/app/modules/program-dashboard/pipes/filterChart/filter-chart.pipe.ts
  src/app/client/src/app/modules/program-dashboard/program-dashboard.module.ts
  src/app/client/src/app/modules/program-dashboard/shared/sb-bignumber/sb-bignumber.component.html
  src/app/client/src/app/modules/program-dashboard/shared/sb-bignumber/sb-bignumber.component.scss
  src/app/client/src/app/modules/program-dashboard/shared/sb-bignumber/sb-bignumber.component.spec.data.ts
  src/app/client/src/app/modules/program-dashboard/shared/sb-bignumber/sb-bignumber.component.spec.ts
  src/app/client/src/app/modules/program-dashboard/shared/sb-bignumber/sb-bignumber.component.ts
  src/app/client/src/app/modules/program-dashboard/shared/sb-chart/sb-chart.component.html
  src/app/client/src/app/modules/program-dashboard/shared/sb-chart/sb-chart.component.scss
  src/app/client/src/app/modules/program-dashboard/shared/sb-chart/sb-chart.component.spec.data.ts
  src/app/client/src/app/modules/program-dashboard/shared/sb-chart/sb-chart.component.spec.ts
  src/app/client/src/app/modules/program-dashboard/shared/sb-chart/sb-chart.component.ts
  src/app/client/src/app/modules/program-dashboard/shared/sb-table/sb-table.component.html
  src/app/client/src/app/modules/program-dashboard/shared/sb-table/sb-table.component.scss
  src/app/client/src/app/modules/program-dashboard/shared/sb-table/sb-table.component.spec.data.ts
  src/app/client/src/app/modules/program-dashboard/shared/sb-table/sb-table.component.spec.ts
  src/app/client/src/app/modules/program-dashboard/shared/sb-table/sb-table.component.ts
  src/app/client/yarn.lock
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/json/en.json
Labels: Feature, story

#8227 Issue #SB-30707 fix: Mentor list dropdown issue fixed.
  src/app/client/src/app/modules/learn/components/batch/create-batch/create-batch.component.ts
  src/app/client/src/app/modules/learn/components/course-consumption/course-player/course-player.component.ts
Labels: defect, regression

#8228 Issue #SB-30731 fix: Board label in hindi properties file updated
  src/app/resourcebundles/data/consumption/hi.properties
  src/app/resourcebundles/json/hi.json
Labels: defect, regression

#8233 Issue #SB-30708 #SB-30727 fix: Disable user on boarding workflow for managed user and SSO user
  src/app/client/src/app/app.component.ts
Labels: defect, regression

#8231 Issue #SB-29906 fix: Deselection of filters based on deselection of d…
  src/app/client/src/app/modules/dashboard/components/filter/filter.component.spec.data.ts
  src/app/client/src/app/modules/dashboard/components/filter/filter.component.spec.ts
  src/app/client/src/app/modules/dashboard/components/filter/filter.component.ts
Labels: enhancement

#8235 Issue #SB-30707 fix: Mentor and participant list dropdown migration
  src/app/client/src/app/modules/learn/components/batch/create-batch/create-batch.component.html
  src/app/client/src/app/modules/learn/components/batch/create-batch/create-batch.component.ts
  src/app/client/src/app/modules/learn/components/batch/update-course-batch/update-course-batch.component.html
  src/app/client/src/app/modules/learn/components/batch/update-course-batch/update-course-batch.component.ts
Labels: defect, regression, material-ui

#8237 Issue #SB-30710 fix: Reverted moment npm version
  src/app/client/package.json
  src/app/client/yarn.lock
Labels: defect, regression

#8242 Issue #SB-00000 fix: Merge release-4.10.2into release-4.10.3
  src/app/client/angular.json
  src/app/client/package.json
  src/app/client/src/app/app.component.ts
  src/app/client/src/app/modules/learn/components/batch/create-batch/create-batch.component.html
  src/app/client/src/app/modules/learn/components/batch/create-batch/create-batch.component.ts
  src/app/client/src/app/modules/learn/components/batch/update-course-batch/update-course-batch.component.html
  src/app/client/src/app/modules/learn/components/batch/update-course-batch/update-course-batch.component.ts
  src/app/client/src/app/modules/learn/components/course-consumption/course-player/course-player.component.ts
  src/app/client/src/app/modules/public/module/signup/components/signup-basic-info/signup-basic-info.component.ts
  src/app/client/src/app/modules/public/module/signup/components/signup/signup.component.scss
  src/app/client/src/app/modules/shared-feature/components/user-onboarding/user-onboarding.component.html
  src/app/client/src/app/modules/shared-feature/components/user-onboarding/user-onboarding.component.scss
  src/app/client/src/app/plugins/location/components/delegate/sb-form-location-options.factory.ts
  src/app/client/src/assets/styles/global.scss
  src/app/client/yarn.lock
  src/app/resourcebundles/data/consumption/hi.properties
  src/app/resourcebundles/json/hi.json
Labels: branch_merge

#8243 Issue #SB-0000 fix: Update portal version to 4.10.3
  src/app/client/package.json
  src/app/package.json
  src/desktop/package.json
Labels: version update

#8244 Issue #SB-0000 fix: Updated documentation
  README.md
  src/app/client/README.md
Labels: documentation

#8245 Issue #SB-30752 fix:observation displayed as per the selected role
  src/app/client/src/app/modules/core/components/content-type/content-type.component.ts
Labels: defect
