Repository Sunbird-Ed/SunbirdEd-portal, pull requests merged in 2023-06, with the labels that each got.

#8744 Issue #ED-1659 fix: block filter dependency issue
  src/app/client/src/app/modules/dashboard/components/filter/filter.component.ts
Labels: bug

#8747 ED-2160 fix: updated the sb-dashlet package
  src/app/client/package.json
  src/app/client/src/app/modules/dashboard/components/sb-table/sb-table.component.ts
  src/app/client/yarn.lock
Labels: angular_upgradation

#8749 ED-2160 fix: updated the sb-dashlet package
  src/app/client/package.json
  src/app/client/yarn.lock
Labels: angular_upgradation

#8752 ED-2160 fix: console de undefind exception
  src/app/client/package.json
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.ts
  src/app/client/src/app/modules/dashboard/dashboard.module.ts
  src/app/client/src/app/modules/program-dashboard/program-dashboard.module.ts
  src/app/client/src/app/modules/report/report.module.ts
  src/app/client/src/app/modules/shared-feature/shared-feature.module.ts
  src/app/client/yarn.lock
Labels: Feature

#8783 Issue Fix #ED-2259: Help Page: User not able to Submit the feedback
  src/app/client/src/app/modules/public/module/help/components/faq-report/faq-report.component.ts
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/json/en.json
Labels: defect

#8787 Issue #SB-0000 fix: solution API added to URL pattern of whitelistAPI file
  src/app/helpers/whitelistApis.js
Labels: defect

#8792 Issue #ED-0000 fix: Changes to get board value from environment variable
  src/app/client/src/app/modules/core/services/user/user.service.ts
  src/app/client/src/index.html
  src/app/helpers/environmentVariablesHelper.js
  src/app/routes/clientRoutes.js
Labels: enhancement

#8794 Issue #SB-0000 fix: Angular issue with selected chart level filters
  src/app/client/src/app/modules/program-dashboard/shared/sb-chart/sb-chart.component.ts
Labels: enhancement

#8796 Issue #ED-0000 updating the dependency from other building blocks
  Dockerfile
  Dockerfile.Build
  README.md
  build.sh
  src/app/client/README.md
  src/app/client/package.json
  src/app/client/yarn.lock
  src/app/package.json
  src/app/yarn.lock
Labels: configuration

#8811 Issue #ED-2364 fix: Selected filters at the chart level showing up for pop-up filter
  src/app/client/src/app/modules/dashboard/components/filter/filter.component.ts
  src/app/client/src/app/modules/program-dashboard/shared/sb-chart/sb-chart.component.html
  src/app/client/src/app/modules/program-dashboard/shared/sb-chart/sb-chart.component.ts
Labels: defect

#8823 Issue #ED-2455 fix:Fixed Activity dashboard button getting displayed whille searching doid from mygroups
  src/app/client/src/app/modules/learn/components/course-consumption/course-consumption-header/course-consumption-header.component.html
  src/app/client/src/app/modules/learn/components/course-consumption/course-consumption-header/course-consumption-header.component.ts
Labels: defect
