Repository Sunbird-Ed/SunbirdEd-portal, pull requests merged in 2023-01, with the labels that each got.

#8457 Issue #ED-804 Improve SunbirdED portal test case
  src/app/client/src/app/modules/core/services/action/action.service.spec.ts
Labels: test_case

#8462 Issue #ED-697 fix: Telemetry data sync
  src/app/client/src/app/modules/shared/components/account-merge-modal/account-merge-modal.component.ts
Labels: defect

#8466 Issue #ED-729 fix: Desktop app download and delete download updated
  src/app/client/src/app/modules/public/module/offline/services/content-manager/content-manager.service.ts
  src/desktop/modules/controllers/content/contentDelete.ts
Labels: defect

#8472 Issue Fix #ED-731 Issue with single page PDF content rating popup and…
  src/app/client/src/app/modules/learn/components/course-consumption/assessment-player/assessment-player.component.ts
  src/app/package.json
Labels: bug

#8471 Issue #ED-874 cleanup and themes cleanup & SASS migration -- converte…
  src/app/client/src/assets/styles/components/_cbse.scss
  src/app/client/src/assets/styles/components/_checkbox.scss
  src/app/client/src/assets/styles/components/_collection-tree.scss
  src/app/client/src/assets/styles/components/_filters.scss
  src/app/client/src/assets/styles/components/_form.scss
  src/app/client/src/assets/styles/components/_lists.scss
  src/desktop/loading/style.css
Labels: enhancement, sass migration

#8468 Issue UPHRH #1193 feat: hide or show language dropdown field from UI through configuration
  src/app/client/src/app/modules/core/components/main-header/main-header.component.html
  src/app/client/src/app/modules/core/components/main-header/main-header.component.ts
Labels: contribution, UPHRH

#8476 Issue #ED-976 Jest test cases for portal
  src/app/client/src/app/modules/core/services/action/action.service.spec.ts
  src/app/client/src/app/modules/core/services/badges/badges.service.spec.ts
  src/app/client/src/app/modules/core/services/course/course.service.spec.ts
  src/app/client/src/app/modules/core/services/org-details/org-details.service.spec.ts
  src/app/client/src/app/modules/core/services/org-details/org-details.service.ts
  src/app/client/src/app/modules/core/services/tnc/tnc.service.spec.ts
Labels: test_case

#8477 Issue #ED-976 fix: Added test cases
  src/app/client/src/app/modules/core/services/tenant/tenant.service.spec.ts
  src/app/client/src/app/modules/dashboard/components/course-dashboard/course-dashboard.component.spec.ts
  src/app/client/yarn.lock
Labels: test_case

#8478 Issue #ED-976 fix: added testcase for otp component
  src/app/client/src/app/modules/public/module/signup/components/otp/otp.component.spec.data.ts
  src/app/client/src/app/modules/public/module/signup/components/otp/otp.component.spec.ts
  src/app/client/src/app/modules/public/module/signup/components/otp/otp.component.ts
Labels: test_case

#8480 Issue #ED-976 Jest test cases for portal
  src/app/client/src/app/modules/core/services/org-details/org-details.service.spec.ts
  src/app/client/src/app/modules/core/services/report/report.service.spec.ts
  src/app/client/src/app/modules/core/services/schema/schema.service.spec.data.ts
  src/app/client/src/app/modules/core/services/schema/schema.service.spec.ts
Labels: test_case

#8482 Issue #ED-1051 fix: Merge release-5.0.0.5 into release-5.1.0
  src/app/client/src/app/modules/learn/components/course-consumption/assessment-player/assessment-player.component.ts
  src/app/client/yarn.lock
  src/app/yarn.lock
Labels: branch_merge

#8481 Issue #Ed 971 Stepper UI Changes.
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.html
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.scss
Labels: Feature

#8486 Issue #ED-1056 fix: Added test case
  src/app/client/src/app/modules/core/services/user/user.service.spec.ts
  src/app/client/src/app/modules/shared-feature/components/content-player/content-player.component.spec.ts
Labels: test_case

#8488 Issue #ED-976 fix:added testcases for questionnaire component
  src/app/client/src/app/modules/public/module/signup/components/otp/otp.component.spec.ts
  src/app/client/src/app/modules/questionnaire/questionnaire/questionnaire.component.spec.ts
Labels: test_case

#8489 Issue #ED-1056 fix: added testcase for course-progress-service
  src/app/client/src/app/modules/dashboard/services/course-progress/course-progress.service.spec.ts
Labels: test_case

#8516 issue #ED-1056 fix: added testcase for content-actions-component
  src/app/client/src/app/modules/player-helper/components/content-actions/content-actions.component.spec.data.ts
  src/app/client/src/app/modules/player-helper/components/content-actions/content-actions.component.spec.ts
Labels: test_case

#8518 Revert "Issue ED-1169 fix: Preprod - Unable to login with existing user"
  src/app/routes/keycloakSignInRoutes.js
Labels: bug

#8519 Issue #ED-1056:Added testcases for signup-email-password component
  src/app/client/src/app/modules/public/module/signup/components/signup-email-password/signup-email-password.component.spec.ts
Labels: test_case

#8520 Issue ED-1169 fix: Preprod - Unable to login with existing user
  src/app/routes/keycloakSignInRoutes.js
Labels: bug

#8521 issue #ED-1056 fix: added testcase for choose-user-component
  src/app/client/src/app/plugins/profile/components/choose-user/choose-user.component.spec.ts
Labels: test_case

#8522 Issue #ED-0000 fix: Updated portal version to 5.1.1
  src/app/client/package.json
  src/app/package.json
  src/desktop/package.json
Labels: version update
