Repository Sunbird-Ed/SunbirdEd-portal, pull requests merged in 2023-02, with the labels that each got.

#8524 Issue #ED-0000 fix: Update node version for desktop build
  Jenkinsfile.desktop
Labels: version update

#8525 Issue #ED-0000 fix: Update node version for desktop build
  Jenkinsfile.desktop
Labels: version update

#8498 Issue #ED-1056 Improve SunbirdED portal test case - 5.1.2
  src/app/client/src/app/modules/core/services/course/course.service.spec.ts
  src/app/client/src/app/modules/core/services/framework/framework.service.spec.ts
Labels: test_case

#8528 Issue #ED-1178 fix: Board name transpose handled
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
Labels: hot-fix

#8530 Issue #ED-1056: Added testcases for app-landing-section and app-loade…
  src/app/client/src/app/modules/shared/components/app-landing-section/app-landing-section.component.spec.ts
  src/app/client/src/app/modules/shared/components/app-loader/app-loader.component.spec.ts
Labels: test_case

#8531 Issue #ED-1197 fix: Merge release-5.1.1 into release-5.1.2
  Jenkinsfile.desktop
  src/app/client/package.json
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.ts
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.ts
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
  src/app/package.json
  src/app/routes/keycloakSignInRoutes.js
  src/desktop/package.json
Labels: branch_merge

#8532 Issue #ED-1197 fix: Merge branch 'release-5.1.2' into release-5.2.0
  Jenkinsfile.desktop
  src/app/client/package.json
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.ts
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.ts
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
  src/app/package.json
  src/app/routes/keycloakSignInRoutes.js
  src/desktop/package.json
Labels: branch_merge

#8534 Issue #ED-0000 fix: Updated portal version
  src/app/client/package.json
  src/app/package.json
  src/desktop/package.json
Labels: version update

#8540 Issue #ED-0000 fix: Updated node version for desktop build
  src/desktop/build.sh
  src/desktop/package.json
Labels: version update

#8541 Issue #ED-0000 fix: Updated node version for desktop build
  src/desktop/package.json
Labels: version update

#8539 Issue #ED-1202: Fixed reset button in filters
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.spec.ts
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.ts
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
Labels: defect

#8543 Issue #ED-1052 fix: ngx-avatar replaced to cc-sb-member-card
  src/app/client/package.json
  src/app/client/src/app/modules/core/components/main-header/main-header.component.html
  src/app/client/src/app/modules/core/components/main-header/main-header.component.scss
  src/app/client/src/app/modules/core/components/main-header/main-header.component.spec.ts
  src/app/client/src/app/modules/core/components/main-header/main-header.component.ts
  src/app/client/src/app/modules/core/components/main-menu/main-menu.component.html
  src/app/client/src/app/modules/core/core.module.ts
  src/app/client/src/app/modules/manage/components/user-role-assign/user-role-assign.component.html
  src/app/client/src/app/modules/manage/components/user-role-assign/user-role-assign.component.scss
  src/app/client/src/app/modules/manage/components/user-role-assign/user-role-assign.component.spec.ts
  src/app/client/src/app/modules/manage/components/user-role-assign/user-role-assign.component.ts
  src/app/client/src/app/modules/manage/manage.module.ts
  src/app/client/src/app/modules/observation/observation.module.ts
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.html
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.scss
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.ts
  src/app/client/src/app/modules/public/module/guest-profile/guest-profile.module.ts
  src/app/client/src/app/modules/search/components/user-search/user-search.component.html
  src/app/client/src/app/modules/search/components/user-search/user-search.component.scss
  src/app/client/src/app/modules/search/components/user-search/user-search.component.ts
  src/app/client/src/app/modules/search/search.module.ts
  src/app/client/src/app/modules/workspace/components/workspacesidebar/workspacesidebar.component.html
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.html
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.scss
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.ts
  src/app/client/src/app/plugins/profile/profile.module.ts
  src/app/client/src/assets/styles/layout/_grid.scss
  src/app/client/yarn.lock
Labels: NG_UPGRADE_CLEANUP

#8544 Issue #ED-0000 fix: Desktop build issue fixed
  Jenkinsfile.desktop
  src/desktop/package.json
Labels: version update

#8546 Issue #ED-1204 - Radio Button and UI text are broken on sync telemetr…
  src/app/client/src/assets/styles/components/_checkbox.scss
  src/app/client/src/assets/styles/components/_collection-tree.scss
  src/app/client/src/assets/styles/components/_filters.scss
  src/app/client/src/assets/styles/components/_form.scss
  src/app/client/src/assets/styles/components/_lists.scss
Labels: bug, ui

#8548 Issue #ED-1203 fix: added test case for telemetry-action-service
  src/app/client/src/app/modules/public/module/offline/services/telemetry-actions/telemetry-actions.service.spec.data.ts
  src/app/client/src/app/modules/public/module/offline/services/telemetry-actions/telemetry-actions.service.spec.ts
Labels: test_case

#8553 Issue #ED-1203 fix: added test case for telemetry-import-component
  src/app/client/src/app/modules/public/module/offline/components/telemetry-import/telemetry-import.component.spec.ts
Labels: test_case

#8558 Issue #ED-0000 fix: Updated desktop package version
  src/desktop/package.json
  src/desktop/yarn.lock
Labels: version update

#8555 Issue #ED-1052: cleanup of angular-inport dependency
  src/app/client/package.json
  src/app/client/src/app/modules/core/services/data/data.service.ts
  src/app/client/src/app/modules/core/services/device-register/device-register.service.ts
  src/app/client/src/app/modules/core/services/user/user.service.ts
  src/app/client/src/app/modules/dashboard/services/report/report.service.ts
  src/app/client/src/app/modules/dial-code-search/components/dial-code/dial-code.component.html
  src/app/client/src/app/modules/dial-code-search/components/dial-code/dial-code.component.ts
  src/app/client/src/app/modules/dial-code-search/dial-code-search.module.ts
  src/app/client/src/app/modules/explore-page/explore-page.module.ts
  src/app/client/src/app/modules/groups/groups.module.ts
  src/app/client/src/app/modules/manage/manage.module.ts
  src/app/client/src/app/modules/observation/components/observation-listing/observation-listing.component.html
  src/app/client/src/app/modules/observation/components/observation-listing/observation-listing.component.ts
  src/app/client/src/app/modules/observation/observation.module.ts
  src/app/client/src/app/modules/org-management/org-management.module.ts
  src/app/client/src/app/modules/program-dashboard/program-dashboard.module.ts
  src/app/client/src/app/modules/public/module/course/components/explore-course/explore-course.component.html
  src/app/client/src/app/modules/public/module/course/course.module.ts
  src/app/client/src/app/modules/public/module/explore/components/explore-content/explore-content.component.html
  src/app/client/src/app/modules/public/module/explore/explore.module.ts
  src/app/client/src/app/modules/public/module/offline/offline.module.ts
  src/app/client/src/app/modules/public/module/sign-in/sso/sso-routing.module.ts
  src/app/client/src/app/modules/public/module/signup/signup-routing.module.ts
  src/app/client/src/app/modules/resource/resource.module.ts
  src/app/client/src/app/modules/search/components/home-search/home-search.component.html
  src/app/client/src/app/modules/search/components/user-search/user-search.component.html
  src/app/client/src/app/modules/search/components/user-search/user-search.component.ts
  src/app/client/src/app/modules/search/search.module.ts
  src/app/client/src/app/modules/shared/components/modal-wrapper/modal-wrapper.component.ts
  src/app/client/src/app/modules/shared/services/genericResource/genericResource.service.ts
  src/app/client/src/app/modules/shared/services/resource/resource.service.ts
  src/app/client/src/app/modules/workspace/components/all-content/all-content.component.html
  src/app/client/src/app/modules/workspace/components/all-content/all-content.component.ts
  src/app/client/src/app/modules/workspace/components/all-textbooks/all-textbooks.component.html
  src/app/client/src/app/modules/workspace/components/all-textbooks/all-textbooks.component.ts
  src/app/client/src/app/modules/workspace/components/batch-list/batch-list.component.html
  src/app/client/src/app/modules/workspace/components/batch-list/batch-list.component.ts
  src/app/client/src/app/modules/workspace/components/collaborating-on/collaborating-on.component.html
  src/app/client/src/app/modules/workspace/components/collaborating-on/collaborating-on.component.ts
  src/app/client/src/app/modules/workspace/components/data-driven/data-driven.component.ts
  src/app/client/src/app/modules/workspace/components/draft/draft.component.html
  src/app/client/src/app/modules/workspace/components/draft/draft.component.ts
  src/app/client/src/app/modules/workspace/components/flag-reviewer/flag-reviewer.component.html
  src/app/client/src/app/modules/workspace/components/flag-reviewer/flag-reviewer.component.ts
  src/app/client/src/app/modules/workspace/components/flagged/flagged.component.html
  src/app/client/src/app/modules/workspace/components/flagged/flagged.component.ts
  src/app/client/src/app/modules/workspace/components/limited-published/limited-published.component.html
  src/app/client/src/app/modules/workspace/components/limited-published/limited-published.component.ts
  src/app/client/src/app/modules/workspace/components/published/published.component.html
  src/app/client/src/app/modules/workspace/components/published/published.component.ts
  src/app/client/src/app/modules/workspace/components/review-submissions/review-submissions.component.html
  src/app/client/src/app/modules/workspace/components/review-submissions/review-submissions.component.ts
  src/app/client/src/app/modules/workspace/components/up-for-review/up-for-review.component.html
  src/app/client/src/app/modules/workspace/components/up-for-review/up-for-review.component.ts
  src/app/client/src/app/modules/workspace/components/uploaded/uploaded.component.html
  src/app/client/src/app/modules/workspace/components/uploaded/uploaded.component.ts
  src/app/client/src/app/modules/workspace/workspace.module.ts
  src/app/client/yarn.lock
Labels: Feature, NG_UPGRADE_CLEANUP

#8559 Issue #ED-0000 fix: Updated desktop package version
  Jenkinsfile.desktop
  build.sh
Labels: version update

#8560 Issue #SB-0000: Merging release-5.1.0.4 into release-5.1.1
  src/app/client/src/app/modules/shared/components/network-status/network-status.component.html
  src/app/client/src/app/modules/workspace/components/content-creation-default-template/content-creation-default-template.component.html
  src/app/client/src/assets/styles/components/_checkbox.scss
  src/app/client/src/assets/styles/components/_collection-tree.scss
  src/app/client/src/assets/styles/components/_form.scss
  src/app/client/src/assets/styles/global.scss
Labels: branch_merge

#8561 Issue #SB-0000: Merging release-5.1.1 into release-5.1.2
  Jenkinsfile.desktop
  src/app/client/src/app/app.component.ts
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.spec.ts
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.ts
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
  src/app/client/src/app/modules/public/module/help/services/faq/faq.service.spec.ts
  src/app/client/src/app/modules/shared/components/network-status/network-status.component.html
  src/app/client/src/app/modules/workspace/components/content-creation-default-template/content-creation-default-template.component.html
  src/app/client/src/assets/styles/components/_checkbox.scss
  src/app/client/src/assets/styles/components/_collection-tree.scss
  src/app/client/src/assets/styles/components/_form.scss
  src/app/client/src/assets/styles/global.scss
  src/desktop/build.sh
  src/desktop/modules/routes/static.ts
  src/desktop/package.json
  src/desktop/yarn.lock
Labels: branch_merge

#8562 Issue #SB-0000: Merging release-5.1.2 into release-5.2.0
  Jenkinsfile.desktop
  src/app/client/src/app/app.component.ts
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.spec.ts
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.ts
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
  src/app/client/src/app/modules/public/module/help/services/faq/faq.service.spec.ts
  src/app/client/src/app/modules/shared/components/network-status/network-status.component.html
  src/app/client/src/app/modules/workspace/components/content-creation-default-template/content-creation-default-template.component.html
  src/app/client/src/assets/styles/components/_checkbox.scss
  src/app/client/src/assets/styles/components/_collection-tree.scss
  src/app/client/src/assets/styles/components/_form.scss
  src/app/client/src/assets/styles/global.scss
  src/desktop/build.sh
  src/desktop/modules/routes/static.ts
  src/desktop/package.json
  src/desktop/yarn.lock
Labels: branch_merge

#8563 Issue #ED-1052: Updated some v12 dependencies
  src/app/client/package.json
  src/app/client/src/app/modules/dashboard/dashboard.module.ts
  src/app/client/src/app/modules/explore-page/explore-page.module.ts
  src/app/client/src/app/modules/program-dashboard/program-dashboard.module.ts
  src/app/client/src/app/modules/public/module/offline/offline.module.ts
  src/app/client/src/app/modules/report/report.module.ts
  src/app/client/src/app/modules/shared-feature/shared-feature.module.ts
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.ts
  src/app/client/src/app/plugins/profile/profile.module.ts
  src/app/client/yarn.lock
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8556 Issue #ED-1052: cleanup of ngx-infinite-scroll dependency
  src/app/client/angular.json
  src/app/client/package.json
  src/app/client/src/app/modules/dial-code-search/components/dial-code/dial-code.component.html
  src/app/client/src/app/modules/dial-code-search/dial-code-search.module.ts
  src/app/client/src/app/modules/discussion/discussion.module.ts
  src/app/client/src/app/modules/observation/components/add-entity/add-entity.component.html
  src/app/client/src/app/modules/observation/observation.module.ts
  src/app/client/src/app/modules/player-helper/player-helper.module.ts
  src/app/client/src/app/modules/player-helper/service/quml-player/quml-player.service.ts
  src/app/client/src/app/modules/report/components/entity-list/entity-list.component.html
  src/app/client/src/app/modules/report/report.module.ts
  src/app/client/src/app/modules/uci-admin/components/uci/uci.component.html
  src/app/client/src/app/modules/uci-admin/uci-admin.module.ts
  src/app/client/src/app/modules/workspace/workspace.module.ts
  src/app/client/src/tsconfig.app.json
  src/app/client/yarn.lock
Labels: Feature, NG_UPGRADE_CLEANUP

#8565 Issue #ED1052 fix: Removing ngx-slick dependencies
  src/app/client/angular.json
  src/app/client/package.json
  src/app/client/src/app/modules/content-search/components/page-section/page-section.component.html
  src/app/client/src/app/modules/content-search/components/page-section/page-section.component.scss
  src/app/client/src/app/modules/content-search/components/page-section/page-section.component.ts
  src/app/client/src/app/modules/content-search/content-search.module.ts
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html
  src/app/client/src/app/modules/explore-page/explore-page.module.ts
  src/app/client/src/app/modules/groups/components/ftu-popup/ftu-popup.component.html
  src/app/client/src/app/modules/groups/groups.module.ts
  src/app/client/src/app/modules/learn/learn.module.ts
  src/app/client/src/app/modules/public/module/explore/explore.module.ts
  src/app/client/src/app/modules/public/module/offline/offline.module.ts
  src/app/client/src/app/modules/resource/resource.module.ts
  src/app/client/src/app/modules/shared-feature/shared-feature.module.ts
  src/app/client/src/app/modules/shared/components/index.ts
  src/app/client/src/app/modules/shared/components/slick/slick.component.html
  src/app/client/src/app/modules/shared/components/slick/slick.component.scss
  src/app/client/src/app/modules/shared/components/slick/slick.component.spec.ts
  src/app/client/src/app/modules/shared/components/slick/slick.component.ts
  src/app/client/src/app/modules/shared/shared.module.ts
  src/app/client/src/app/modules/workspace/workspace.module.ts
  src/app/client/src/app/plugins/profile/profile.module.ts
  src/app/client/src/assets/libs/slick-carousel/package.json
  src/app/client/src/assets/libs/slick-carousel/slick.js
  src/app/client/src/assets/styles/components/_card.scss
  src/app/client/yarn.lock
  src/app/yarn.lock
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8568 Issue #ED-1052 fix: Removing ngx order by pipe dependencies
  src/app/client/package.json
  src/app/client/src/app/modules/dashboard/dashboard.module.ts
  src/app/client/src/app/modules/public/module/offline/components/content-manager/content-manager.component.html
  src/app/client/src/app/modules/public/module/offline/offline.module.ts
  src/app/client/src/app/modules/search/components/user-profile/user-profile.component.html
  src/app/client/src/app/modules/search/search.module.ts
  src/app/client/src/app/modules/workspace/components/collaborating-on/collaborating-on.component.html
  src/app/client/src/app/modules/workspace/components/review-comments/review-comments.component.html
  src/app/client/src/app/modules/workspace/workspace.module.ts
  src/app/client/yarn.lock
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8570 Update build.sh
  src/desktop/build.sh
Labels: patch

#8571 Issue #ED-0000 desktop build issue update
  Jenkinsfile.desktop
  src/desktop/build.sh
  src/desktop/scripts/copy.js
Labels: patch

#8573 Issue #ED-1080 fix:reveted stepper UI changes
  src/app/client/src/app/modules/shared-feature/components/onboarding-user-selection/onboarding-user-selection.component.html
  src/app/client/src/app/modules/shared-feature/components/onboarding-user-selection/onboarding-user-selection.component.scss
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.html
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.scss
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.html
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.scss
Labels: defect

#8574 Issue #ED-1347 fix:updating editor and player version
  src/app/client/angular.json
  src/app/client/package.json
  src/app/client/src/app/modules/player-helper/player-helper.module.ts
  src/app/client/src/app/modules/player-helper/service/quml-player/quml-player.service.ts
  src/app/client/src/app/modules/workspace/workspace.module.ts
  src/app/client/src/tsconfig.app.json
  src/app/client/yarn.lock
Labels: version update

#8575 Issue #ED-0000 patch: express response cleanup for health checkup
  src/app/helpers/healthCheckService.js
Labels: patch, bootcamp
