Repository Sunbird-Ed/SunbirdEd-portal, pull requests merged in 2023-05, with the labels that each got.

#8663 Issue #ED-1754 fix: Updated env url for build testing
  src/desktop/env.json
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8675 Issue #ED-1275 fix:integrated UCI console
  src/app/client/angular.json
  src/app/client/package.json
  src/app/client/src/app/modules/player-helper/player-helper.module.ts
  src/app/client/src/app/modules/uci-admin/components/uci/uci.component.html
  src/app/client/src/app/modules/uci-admin/uci-admin.module.ts
  src/app/client/yarn.lock
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8688 Issue #ED-1817 fix: Jest configuration changes for V14
  .circleci/config.yml
  src/app/client/jest-global-mocks.ts
  src/app/client/jest.config.js
  src/app/client/package.json
  src/app/client/src/app/modules/content-search/components/global-search-filter/global-search-filter.component.ts
  src/app/client/src/app/modules/content-search/components/global-search-selected-filter/global-search-selected-filter.component.ts
  src/app/client/src/app/modules/core/components/main-header/main-header.component.spec.ts
  src/app/client/src/app/modules/dashboard/components/filter/filter.component.spec.ts
  src/app/client/src/app/modules/merge-account/components/merge-account-status/merge-account-status.component.spec.ts
  src/app/client/src/app/modules/player-helper/components/content-actions/content-actions.component.spec.ts
  src/app/client/src/app/modules/shared-feature/components/sso-merge-confirmation/sso-merge-confirmation.component.spec.ts
  src/app/client/src/app/modules/shared/components/account-merge-modal/account-merge-modal.component.spec.ts
  src/app/client/src/app/modules/shared/services/config/config.service.spec.ts
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.spec.ts
  src/app/client/tsconfig.spec.json
  src/app/client/yarn.lock
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8699 Issue #ED-1276 fix: Added styles path to discussions-ui
  src/app/client/angular.json
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8700 ED-2027 fix: dashboard global filter issue
  src/app/client/src/app/modules/dashboard/components/filter/filter.component.ts
  src/app/client/src/app/modules/dashboard/dashboard.module.ts
  src/app/client/yarn.lock
Labels: bug, angular_upgradation

#8715 #ED-94 fix:Program dashboard minor ui issues
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.html
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
Labels: bug, ui

#8716 Issue #ED-419 fix: ouptut event added for successful consent update
  src/app/client/src/app/modules/observation/components/observation-details/observation-details.component.html
  src/app/client/src/app/modules/observation/components/observation-details/observation-details.component.ts
  src/app/client/src/app/modules/shared-feature/components/global-consent-pii/global-consent-pii.component.ts
Labels: bug

#8719 ED-2098 feat:copy question set api integration
  src/app/client/src/app/modules/core/services/copy-content/copy-content.service.ts
  src/app/routes/contentRoutes.js
Labels: Feature

#8720 ED-2098 feat: redirection issue fixed
  src/app/client/src/app/modules/core/services/copy-content/copy-content.service.ts
Labels: Feature

#8726 Issue #ED-94 fix: config modified as required by sb-dashlet and filter components
  src/app/client/src/app/modules/program-dashboard/shared/sb-chart/sb-chart.component.ts
Labels: defect

#8732 Issue #ED-1695 fix: deselection of dependent filter deselects the dependent filter
  src/app/client/src/app/modules/dashboard/components/filter/filter.component.ts
Labels: bug

#8733 #SB-0000 merge : 6.0v14 into release-6.0.0
  src/app/client/src/app/modules/dashboard/components/filter/filter.component.ts
  src/app/routes/contentRoutes.js
Labels: Feature

#8734 ED-2098 feat: refactor contentroute js file
  src/app/routes/contentRoutes.js
Labels: documentation

#8738 ED-2139 fix:enabled question set for creator role
  src/app/client/src/app/modules/workspace/components/create-content/create-content.component.html
Labels: story
