Repository Sunbird-Ed/SunbirdEd-portal, pull requests merged in 2023-07, with the labels that each got.

#8826 Issue #ED-0000 fix: Upgrade node in desktop build
  Jenkinsfile.desktop
  src/desktop/package.json
Labels: dependencies

#8831 Issue #ED-433 fix: configurable dataset for reports
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
Labels: defect

#8838 Issue #ED-2531 fix: Time range filters depends on the selection of the mandatory filter
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.html
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
Labels: defect

#8839 Issue #ED-0000 fix: Offline installer build and deploy issue fixed
  Jenkinsfile.desktop
  src/app/client/package.json
  src/app/client/yarn.lock
  src/app/yarn.lock
  src/desktop/build.sh
  src/desktop/package.json
  src/desktop/yarn.lock
Labels: desktop

#8843 Issue #ED-0000 fix: [Code Cleanup] Cloud specific references packages are removed
  src/app/helpers/desktopCrashReporter.js
  src/app/helpers/reportHelper.js
  src/app/package.json
  src/app/routes/desktopAppRoutes.js
  src/app/tests/server/helpers/spec/reportHelper.spec.js
Labels: enhancement

#8845 Issue #ED-2572 fix: Custom error for tables in program dashboard
  src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.html
Labels: defect

#8846 Issue #ED-0000 fix: Build issue
  src/app/routes/desktopAppRoutes.js
Labels: configuration

#8847 Issue #ED-0000 fix: Update readme
  README.md
Labels: documentation
