Repository Sunbird-Ed/SunbirdEd-portal, pull requests merged in 2023-03, with the labels that each got.

#8579 Issue #ED-0000 environment variables updated
  src/app/helpers/environmentVariablesHelper.js
Labels: bootcamp

#8580 Issue #ED-0000 label changes
  src/app/client/src/app/modules/core/components/content-type/content-type.component.ts
Labels: enhancement, bootcamp

#8582 Issue #ED-1361 fix: Fix state dropdown reset on clear button
  src/app/client/src/app/plugins/location/components/delegate/sb-form-location-selection.delegate.ts
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.html
Labels: defect

#8583 Issue #ED-1312: Angular 13 Migration changes
  .gitignore
  Jenkinsfile
  src/app/client/angular.json
  src/app/client/jest.config.js
  src/app/client/package.json
  src/app/client/src/app/app.component.ts
  src/app/client/src/app/app.module.ts
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.spec.ts
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.ts
  src/app/client/src/app/modules/core/components/content-type/content-type.component.ts
  src/app/client/src/app/modules/core/components/search/search.component.spec.ts
  src/app/client/src/app/modules/core/services/course/course.service.spec.ts
  src/app/client/src/app/modules/core/services/framework/framework.service.spec.ts
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.ts
  src/app/client/src/app/modules/dashboard/dashboard.module.ts
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
  src/app/client/src/app/modules/player-helper/components/content-actions/content-actions.component.spec.data.ts
  src/app/client/src/app/modules/player-helper/components/content-actions/content-actions.component.spec.ts
  src/app/client/src/app/modules/public/module/help/services/faq/faq.service.spec.ts
  src/app/client/src/app/modules/public/module/offline/components/telemetry-import/telemetry-import.component.spec.ts
  src/app/client/src/app/modules/public/module/offline/offline.module.ts
  src/app/client/src/app/modules/public/module/offline/services/telemetry-actions/telemetry-actions.service.spec.data.ts
  src/app/client/src/app/modules/public/module/offline/services/telemetry-actions/telemetry-actions.service.spec.ts
  src/app/client/src/app/modules/public/module/signup/components/signup-email-password/signup-email-password.component.spec.ts
  src/app/client/src/app/modules/shared-feature/components/onboarding-user-selection/onboarding-user-selection.component.html
  src/app/client/src/app/modules/shared-feature/components/onboarding-user-selection/onboarding-user-selection.component.scss
  src/app/client/src/app/modules/shared/components/app-landing-section/app-landing-section.component.spec.ts
  src/app/client/src/app/modules/shared/components/app-loader/app-loader.component.spec.ts
  src/app/client/src/app/modules/shared/components/network-status/network-status.component.html
  src/app/client/src/app/modules/shared/services/cache-service/cache.service.ts
  src/app/client/src/app/modules/shared/shared.module.ts
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.html
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.scss
  src/app/client/src/app/modules/workspace/components/content-creation-default-template/content-creation-default-template.component.html
  src/app/client/src/app/plugins/location/components/delegate/sb-form-location-selection.delegate.ts
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.html
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.scss
  src/app/client/src/app/plugins/profile/components/choose-user/choose-user.component.spec.ts
  src/app/client/src/app/plugins/profile/components/choose-user/choose-user.component.ts
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.spec.ts
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.ts
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.spec.data.ts
  src/app/client/src/assets/styles/components/_checkbox.scss
  src/app/client/src/assets/styles/components/_collection-tree.scss
  src/app/client/src/assets/styles/components/_form.scss
  src/app/client/src/assets/styles/global.scss
  src/app/client/src/polyfills.ts
  src/app/client/tsconfig.spec.json
  src/app/client/yarn.lock
  src/app/helpers/healthCheckService.js
  src/app/package.json
  src/app/routes/keycloakSignInRoutes.js
  src/desktop/build.sh
  src/desktop/modules/routes/static.ts
  src/desktop/package.json
  src/desktop/scripts/copy.js
  src/desktop/yarn.lock
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8584 Issue #ED-1312 refactor: Updated dependencies to v13
  src/app/client/package.json
  src/app/client/src/app/app.module.ts
  src/app/client/src/app/modules/content-search/components/global-search-filter/global-search-filter.component.spec.ts
  src/app/client/src/app/modules/content-search/components/global-search-filter/global-search-filter.component.ts
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.ts
  src/app/client/src/app/modules/content-search/content-search.module.ts
  src/app/client/src/app/modules/dashboard/components/add-summary-modal/add-summary-modal.component.spec.ts
  src/app/client/src/app/modules/public/module/help/help.module.ts
  src/app/client/src/app/modules/shared-feature/shared-feature.module.ts
  src/app/client/src/app/plugins/location/components/delegate/sb-form-location-options.factory.ts
  src/app/client/src/app/plugins/location/components/delegate/sb-form-location-selection.delegate.ts
  src/app/client/src/app/plugins/location/location.module.ts
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.ts
  src/app/client/src/app/plugins/profile/components/submit-teacher-details/submit-teacher-details.component.spec.data.ts
  src/app/client/src/app/plugins/profile/components/submit-teacher-details/submit-teacher-details.component.ts
  src/app/client/src/app/plugins/profile/profile.module.ts
  src/app/client/yarn.lock
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8586 Issue #ED-1500 Portal: MY Groups : In the popup the X icon distorted.
  src/app/client/src/app/modules/groups/components/popup/popup.component.html
Labels: defect

#8588 Issue #ED-1052 refactor:integrated sb-avatar
  src/app/client/package.json
  src/app/client/src/app/modules/core/components/main-header/main-header.component.html
  src/app/client/src/app/modules/core/components/main-header/main-header.component.scss
  src/app/client/src/app/modules/core/components/main-header/main-header.component.ts
  src/app/client/src/app/modules/core/core.module.ts
  src/app/client/src/app/modules/manage/components/user-role-assign/user-role-assign.component.html
  src/app/client/src/app/modules/manage/components/user-role-assign/user-role-assign.component.ts
  src/app/client/src/app/modules/manage/manage.module.ts
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.html
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.scss
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.ts
  src/app/client/src/app/modules/public/module/guest-profile/guest-profile.module.ts
  src/app/client/src/app/modules/search/components/user-search/user-search.component.html
  src/app/client/src/app/modules/search/components/user-search/user-search.component.ts
  src/app/client/src/app/modules/search/search.module.ts
  src/app/client/src/app/modules/shared/services/config/constants.json
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.html
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.scss
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.ts
  src/app/client/src/app/plugins/profile/profile.module.ts
  src/app/client/yarn.lock
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8587 Issue #ED-1312 feat: Updated the sb-notification dependency to v13
  src/app/client/package.json
  src/app/client/yarn.lock
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8585 Issue #ED-1469 fix: UI multiselect caret and #ED-1482 fix: Files upto 50MB can be attached in observation
  src/app/client/package.json
  src/app/client/src/app/modules/dashboard/components/sb-table/sb-table.component.scss
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.html
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.scss
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.spec.ts
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.ts
  src/app/client/src/app/modules/shared/services/config/url.config.json
  src/app/client/yarn.lock
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/json/en.json
Labels: defect

#8597 Issue #ED-0000 merging release-5.2.0 into 5.2.0_WorkingV12 branch
  Jenkinsfile
  src/app/client/package.json
  src/app/client/src/app/app.component.ts
  src/app/client/src/app/modules/certificate/components/certificate-configuration/certificate-configuration.component.html
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.spec.ts
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.ts
  src/app/client/src/app/modules/core/components/content-type/content-type.component.ts
  src/app/client/src/app/modules/core/services/course/course.service.spec.ts
  src/app/client/src/app/modules/core/services/framework/framework.service.spec.ts
  src/app/client/src/app/modules/dashboard/components/add-summary-modal/add-summary-modal.component.html
  src/app/client/src/app/modules/dashboard/components/course-progress/course-progress.component.html
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.ts
  src/app/client/src/app/modules/dashboard/components/organization/organization.component.html
  src/app/client/src/app/modules/dashboard/components/sb-table/sb-table.component.scss
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
  src/app/client/src/app/modules/groups/components/popup/popup.component.html
  src/app/client/src/app/modules/player-helper/components/content-actions/content-actions.component.spec.data.ts
  src/app/client/src/app/modules/player-helper/components/content-actions/content-actions.component.spec.ts
  src/app/client/src/app/modules/public/module/help/services/faq/faq.service.spec.ts
  src/app/client/src/app/modules/public/module/offline/components/telemetry-import/telemetry-import.component.spec.ts
  src/app/client/src/app/modules/public/module/offline/services/telemetry-actions/telemetry-actions.service.spec.data.ts
  src/app/client/src/app/modules/public/module/offline/services/telemetry-actions/telemetry-actions.service.spec.ts
  src/app/client/src/app/modules/public/module/signup/components/signup-email-password/signup-email-password.component.spec.ts
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.html
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.scss
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.spec.ts
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.ts
  src/app/client/src/app/modules/shared-feature/components/onboarding-user-selection/onboarding-user-selection.component.html
  src/app/client/src/app/modules/shared-feature/components/onboarding-user-selection/onboarding-user-selection.component.scss
  src/app/client/src/app/modules/shared/components/app-landing-section/app-landing-section.component.spec.ts
  src/app/client/src/app/modules/shared/components/app-loader/app-loader.component.spec.ts
  src/app/client/src/app/modules/shared/components/network-status/network-status.component.html
  src/app/client/src/app/modules/shared/services/config/url.config.json
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.html
  src/app/client/src/app/modules/user-onboarding/components/onboarding-popup/onboarding-popup.component.scss
  src/app/client/src/app/modules/workspace/components/content-creation-default-template/content-creation-default-template.component.html
  src/app/client/src/app/plugins/location/components/delegate/sb-form-location-selection.delegate.ts
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.html
  src/app/client/src/app/plugins/location/components/location-selection/location-selection.component.scss
  src/app/client/src/app/plugins/profile/components/choose-user/choose-user.component.spec.ts
  src/app/client/src/app/plugins/profile/components/choose-user/choose-user.component.ts
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.spec.ts
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.ts
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.spec.data.ts
  src/app/client/src/assets/styles/components/_checkbox.scss
  src/app/client/src/assets/styles/components/_collection-tree.scss
  src/app/client/src/assets/styles/components/_form.scss
  src/app/client/src/assets/styles/global.scss
  src/app/helpers/healthCheckService.js
  src/app/helpers/whitelistApis.js
  src/app/package.json
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/json/en.json
  src/app/routes/keycloakSignInRoutes.js
  src/desktop/build.sh
  src/desktop/modules/routes/static.ts
  src/desktop/package.json
  src/desktop/scripts/copy.js
  src/desktop/yarn.lock
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8598 Issue #ED-0000 refactor: Merging v12 into v13
  src/app/client/src/app/modules/certificate/components/certificate-configuration/certificate-configuration.component.html
  src/app/client/src/app/modules/dashboard/components/add-summary-modal/add-summary-modal.component.html
  src/app/client/src/app/modules/dashboard/components/course-progress/course-progress.component.html
  src/app/client/src/app/modules/dashboard/components/organization/organization.component.html
  src/app/client/src/app/modules/dashboard/components/sb-table/sb-table.component.scss
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.html
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.scss
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.spec.ts
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.ts
  src/app/client/src/app/modules/shared/services/config/url.config.json
  src/app/helpers/whitelistApis.js
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/json/en.json
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8599 Issue #ED-1313 fix: Merge 6.0v13 into 6.0v14
  src/app/client/package.json
  src/app/client/src/app/modules/certificate/components/certificate-configuration/certificate-configuration.component.html
  src/app/client/src/app/modules/core/components/main-header/main-header.component.html
  src/app/client/src/app/modules/core/components/main-header/main-header.component.scss
  src/app/client/src/app/modules/core/components/main-header/main-header.component.ts
  src/app/client/src/app/modules/core/core.module.ts
  src/app/client/src/app/modules/dashboard/components/add-summary-modal/add-summary-modal.component.html
  src/app/client/src/app/modules/dashboard/components/course-progress/course-progress.component.html
  src/app/client/src/app/modules/dashboard/components/organization/organization.component.html
  src/app/client/src/app/modules/dashboard/components/sb-table/sb-table.component.scss
  src/app/client/src/app/modules/explore-page/explore-page.module.ts
  src/app/client/src/app/modules/groups/components/popup/popup.component.html
  src/app/client/src/app/modules/manage/components/user-role-assign/user-role-assign.component.html
  src/app/client/src/app/modules/manage/components/user-role-assign/user-role-assign.component.ts
  src/app/client/src/app/modules/manage/manage.module.ts
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.html
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.scss
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.ts
  src/app/client/src/app/modules/public/module/guest-profile/guest-profile.module.ts
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.html
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.scss
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.spec.ts
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.ts
  src/app/client/src/app/modules/search/components/user-search/user-search.component.html
  src/app/client/src/app/modules/search/components/user-search/user-search.component.ts
  src/app/client/src/app/modules/search/search.module.ts
  src/app/client/src/app/modules/shared/services/config/constants.json
  src/app/client/src/app/modules/shared/services/config/url.config.json
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.html
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.scss
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.spec.ts
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.ts
  src/app/client/src/app/plugins/profile/profile.module.ts
  src/app/client/yarn.lock
  src/app/helpers/whitelistApis.js
  src/app/resourcebundles/data/consumption/en.properties
  src/app/resourcebundles/json/en.json
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8603 Issue #ED-1313 fix: Updated portal dependencies for NG 14
  src/app/client/package.json
  src/app/client/src/app/modules/dashboard/dashboard.module.ts
  src/app/client/src/app/modules/program-dashboard/program-dashboard.module.ts
  src/app/client/src/app/modules/report/components/all-evidence/all-evidence.component.scss
  src/app/client/src/app/modules/report/report.module.ts
  src/app/client/src/app/modules/shared-feature/shared-feature.module.ts
  src/app/client/yarn.lock
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8604 Issue #ED-1520 Accessibility: In Admin dashboard, selected tenant parameter with keyboard is not getting highlighted with 2x padding.
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.html
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.scss
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.ts
  src/app/client/src/app/modules/report/components/solution-listing/solution-listing.component.html
Labels: defect, ui

#8606 Issue #ED-0000 fix: Dev testing changes
  src/app/client/src/app/modules/shared/services/cache-service/cache.service.ts
  src/app/client/src/index.html
  src/app/routes/clientRoutes.js
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8607 Issue #ED-0000 fix: Dev testing changes
  src/app/routes/clientRoutes.js
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP
