Repository Sunbird-Ed/SunbirdEd-portal, pull requests merged in 2023-04, with the labels that each got.

#8609 Issue ED-1312: Dev fixes for Angular 13
  src/app/client/package.json
  src/app/client/src/app/modules/shared/services/cache-service/cache.service.ts
  src/app/client/src/index.html
  src/app/routes/clientRoutes.js
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8613 Issue #ED-1312 fix: Collection editor changes
  src/app/client/angular.json
  src/app/client/package.json
  src/app/client/src/app/modules/player-helper/service/quml-player/quml-player.service.ts
  src/app/client/src/app/modules/workspace/workspace.module.ts
  src/app/client/src/tsconfig.app.json
  src/app/client/yarn.lock
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8614 Issue #ED-1600 refactor: video-player as web-component & merging v13
  .circleci/config.yml
  src/app/client/angular.json
  src/app/client/package.json
  src/app/client/src/app/app.module.ts
  src/app/client/src/app/modules/player-helper/player-helper.module.ts
  src/app/client/src/app/modules/public/module/help/help.module.ts
  src/app/client/src/app/modules/shared/services/cache-service/cache.service.ts
  src/app/client/src/app/modules/user-onboarding/user-onboarding.module.ts
  src/app/client/src/assets/sunbird-folder/sunbird-video-player/styles.css
  src/app/client/src/assets/sunbird-folder/sunbird-video-player/video-player.js
  src/app/client/src/index.html
  src/app/client/yarn.lock
  src/app/routes/clientRoutes.js
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8610 Issue #ED-1313 fix: Merge NG13 into NG14
  .circleci/config.yml
  src/app/client/package.json
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8621 6.0v13
  src/app/client/src/app/modules/public/module/course/components/explore-course/explore-course.component.ts
  src/app/client/src/app/modules/public/module/explore/components/explore-content/explore-content.component.ts
Labels: bug

#8623 Issue #ED-1751 fix: Merging release-5.2.0 into v12
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.html
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.scss
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.ts
  src/app/client/src/app/modules/report/components/solution-listing/solution-listing.component.html
  src/app/helpers/whitelistApis.js
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8624 Issue #ED-1748 fix Unable to see content in some filters is applied
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
Labels: defect

#8625 Issue #ED-1748 fix Unable to see content in some filters is applied
  src/app/client/src/app/modules/public/module/explore/components/explore-content/explore-content.component.ts
Labels: defect

#8626 Issue ED-1735 fix:on reload UI is breaking
  src/app/client/src/index.html
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8628 Issue #ED-1748 fix Unable to see content in some filters is applied
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
  src/app/client/src/app/modules/public/module/explore/components/explore-content/explore-content.component.ts
Labels: bug

#8631 Issue #ED-1751 fix: Merging release-v13 into v14
  src/app/client/src/app/modules/content-search/components/search-filter/search-filter.component.ts
  src/app/client/src/app/modules/core/services/search/search.service.spec.ts
  src/app/client/src/app/modules/core/services/search/search.service.ts
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.html
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.scss
  src/app/client/src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.ts
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.html
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.spec.data.ts
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
  src/app/client/src/app/modules/player-helper/components/content-actions/content-actions.component.ts
  src/app/client/src/app/modules/public/module/course/components/explore-course/explore-course.component.ts
  src/app/client/src/app/modules/public/module/explore/components/explore-content/explore-content.component.ts
  src/app/client/src/app/modules/public/module/guest-profile/components/guest-profile/guest-profile.component.html
  src/app/client/src/app/modules/public/module/offline/components/library/library.component.ts
  src/app/client/src/app/modules/report/components/solution-listing/solution-listing.component.html
  src/app/client/src/app/modules/search/components/home-search/home-search.component.spec.data.ts
  src/app/client/src/app/modules/search/components/home-search/home-search.component.ts
  src/app/client/src/app/modules/shared-feature/components/profile-framework-popup/profile-framework-popup.component.html
  src/app/client/src/app/modules/shared-feature/components/profile-framework-popup/profile-framework-popup.component.ts
  src/app/client/src/app/modules/shared/components/select-option-group/select-option-group.component.html
  src/app/client/src/app/modules/shared/components/select-option-group/select-option-group.component.ts
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.html
  src/app/helpers/whitelistApis.js
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8632 Issue #ED-1751 fix: Merging release-5.2.0 into v12
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
  src/app/client/src/app/modules/public/module/explore/components/explore-content/explore-content.component.ts
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8633 Issue #ED-1751 fix: Merging v12 into v13
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
  src/app/client/src/app/modules/public/module/explore/components/explore-content/explore-content.component.ts
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8634 Issue #ED-1751 fix: Merging v13 into v14
  src/app/client/src/app/modules/explore-page/components/explore-page/explore-page.component.ts
  src/app/client/src/app/modules/public/module/explore/components/explore-content/explore-content.component.ts
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8635 Issue ED-1600 fix: removed video&epub as web-component player
  src/app/client/angular.json
  src/app/client/src/app/app.module.ts
  src/app/client/src/app/modules/player-helper/player-helper.module.ts
  src/app/client/src/app/modules/public/module/help/help.module.ts
  src/app/client/src/app/modules/user-onboarding/user-onboarding.module.ts
  src/app/client/src/assets/sunbird-folder/sunbird-epub-player/epub-player.js
  src/app/client/src/assets/sunbird-folder/sunbird-epub-player/styles.css
  src/app/client/src/assets/sunbird-folder/sunbird-epub-player/sunbird-epub-player.js
  src/app/client/src/assets/sunbird-folder/sunbird-video-player/styles.css
  src/app/client/src/assets/sunbird-folder/sunbird-video-player/video-player.js
  src/app/client/src/index.html
  src/app/client/yarn.lock
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8636 Issue #ED-0000 fix: Removed cbse/ncert from aria label in profile-framework popup
  src/app/client/src/app/modules/shared-feature/components/profile-framework-popup/profile-framework-popup.component.html
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8646 Issue #ED-1876 fix: Updated contributions card to new layout
  src/app/client/src/app/plugins/profile/components/profile-page/profile-page.component.html
Labels: defect, angular_upgradation, NG_UPGRADE_CLEANUP

#8649 Issue #SB-0000 fix: observation lisiting page error fix
  src/app/client/src/app/modules/core/services/observation-util/observation-util.service.spec.ts
  src/app/client/src/app/modules/core/services/observation-util/observation-util.service.ts
Labels: bug

#8651 Issue #ED-0000 fix: Portal version update and merge desktop branch changes
  src/app/client/package.json
  src/app/package.json
  src/desktop/OpenRAP/yarn.lock
  src/desktop/main.ts
  src/desktop/modules/manager/contentDownloadManager/ContentDownloader.ts
  src/desktop/modules/manager/contentImportManager/contentImport.ts
  src/desktop/modules/manager/contentImportManager/contentImportHelper.ts
  src/desktop/modules/utils/util.ts
  src/desktop/package.json
  src/desktop/yarn.lock
Labels: version update, branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8657 Issue SB-0000 fix: added timer to upload tab
  src/app/client/src/app/modules/workspace/components/content-editors/collection-editor/collection-editor.component.ts
  src/app/client/src/app/modules/workspace/components/content-editors/content-editor/content-editor.component.ts
  src/app/client/src/app/modules/workspace/components/content-editors/generic-editor/generic-editor.component.ts
Labels: angular_upgradation, NG_UPGRADE_CLEANUP

#8658 Issue SB-0000 fix: updated izimodal package
  src/app/client/package.json
  src/app/client/yarn.lock
Labels: branch_merge, angular_upgradation, NG_UPGRADE_CLEANUP

#8660 SL-Questionnaire library upgraded to Angular version 14
  src/app/client/package.json
  src/app/client/yarn.lock
Labels: angular_upgradation, NG_UPGRADE_CLEANUP
